<?php

/**
 * @file sig_press.module
 * @author Jacek Szmit
 */

define('SIG_PRESS_XML_FETCH_URL', 'http://www.ark.be/nl/api/pressroomRss?client=sig%20air%20handling');
define('SIG_PRESS_XML_FILENAME', 'sig.xml');

/**
 * Implements hook_block_info().
 */
function sig_press_block_info() {
  $blocks = array();

  $blocks['sig_pressroom'] = array(
      'info' => t('SIG pressroom'),
      'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function sig_press_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'sig_pressroom':
      $block['subject'] = t('Sig pressroom');
      $block['content'] = _sig_press_list_articles();
      
      break;
  }
  return $block;
}

/**
 * Implements hook_cron().
 */
function sig_press_cron() {
  module_load_include('inc', 'sig_press', 'sig_press');
  _sig_press_fetch_xml_file();
}

function _sig_press_list_articles() {
  module_load_include('inc', 'sig_press', 'sig_press');
  
  $array = _sig_press_process_xml();
  $lang = _sig_press_get_lang();
  
  $html = '';
  
  if(isset($array[$lang])) {
    if (isset($_GET['pressart']) && isset($array[$lang][(int)$_GET['pressart']])) {
      $item = $array[$lang][(int)$_GET['pressart']];
      $html .= '<div class="press-full">';
      $html .= _sig_press_prepare_item_full($item);
      $html .= '</div>';
    }
    else {
      $html .= '<div class="press-list">';
      foreach($array[$lang] as $index => $item) {
        $html .= '<div class="press-row">';
        $html .= _sig_press_prepare_item_teaser($item, $index);
        $html .= '</div>';
      }
      $html .= '</div>';
    }
  }
  
  return $html;
  
}

/**
 * Prepare full view for pressroom article item
 *
 * @param array $item
 * @return string
 *   HTML
 */
function _sig_press_prepare_item_full($item) {
  $html = '<div class="press-item">';
  $html .= sprintf('<div class="press-date">%s</div>', $item['date']);
  $html .= sprintf('<div class="press-image"><img src="%s" /></div>', $item['image']);
  $html .= sprintf('<div class="press-title">%s</div>', $item['title']);
  $html .= sprintf('<div class="press-body">%s</div>', $item['body']);

  foreach($item['attachments'] as $index => $section) {
    $html .= sprintf('<div class="press-item-section press-item-section-%s">', $index);
    $html .= sprintf('<div class="section-title">%s</div>', $section['title']);
    $html .= sprintf('<div class="section-body">%s</div>', $section['body']);
    $html .= sprintf('<div class="section-url">%s</div>', $section['url']);
    $html .= '<div class="section-files">';
    foreach($section['files'] as $file) {
      if($file['is_image'] == 'true') {
        $html .= sprintf('<img src="%s" />', $file['url']);
      }
      else {
        $html .= sprintf('<a href="%s" target="_blank">%s</a>', $file['url'], $file['url']);
      }
    }
    $html .= '</div>';
    $html .= '</div>';
  }

  $html .= '</div>';

  return $html;
}

/**
 * Prepare teaser view for pressroom article item
 *
 * @param array $item
 * @return string
 *   HTML
 */
function _sig_press_prepare_item_teaser($item, $index) {
  
  $body = strip_tags($item['body']);
  $body = truncate_utf8($body, 400, true);
  $body .= ' ...';
  
  $url = '/' . drupal_get_path_alias(current_path());
  $url .= '?pressart=' . $index;
  
  $read_more_text = t('Read more');
  $read_more = sprintf('<a href="%s">%s</a>', $url, $read_more_text);
  
  $html = '<div class="press-item">';
  $html .= sprintf('<div class="press-image"><img src="%s" /></div>', $item['image']);
  $html .= sprintf('<div class="press-title"><h2><a href="%s">%s</a></h2></div>', $url, $item['title']);
  $html .= sprintf('<div class="press-body">%s%s</div>', $body, $read_more);
  $html .= sprintf('<div class="press-date">%s</div>', $item['date']);

  $html .= '</div>';

  return $html;
}